---
abstract: 'Basic utilities for writing tests.'
author:
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Simple
no_index:
  directory:
    - t
    - inc
    - lib/TB2/Mouse/
  file:
    - lib/TB2/Mouse.pm
requires:
  Test::Harness: 2.03
  perl: 5.008001
resources:
  bugtracker: http://github.com/schwern/test-more/issues/labels/Test-Builder2
  homepage: http://test-more.googlecode.com
  license: http://dev.perl.org/licenses/
  repository: http://github.com/schwern/test-more/tree/Test-Builder2
  x_MailingList: http://groups.google.com/group/test-more-users
version: 1.005000_005
