--- #YAML:1.0
name:                Test-Simple
version:             0.76_02
abstract:            Basic utilities for writing tests.
license:             perl
author:              
    - Michael G Schwern <schwern@pobox.com>
generated_by:        ExtUtils::MakeMaker version 6.43_01
distribution_type:   module
requires:     
    Test::Harness:                 2.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
