--- #YAML:1.0
name:               Test-Simple
version:            0.90
abstract:           Basic utilities for writing tests.
author:
    - Michael G Schwern <schwern@pobox.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Harness:  2.03
resources:
    bugtracker:   http://code.google.com/p/test-more/issues
    homepage:     http://test-more.googlecode.com
    license:      http://dev.perl.org/licenses/
    MailingList:  http://groups.google.com/group/test-more-users
    repository:   http://github.com/schwern/test-more/tree/master
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.53_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
