--- #YAML:1.0
name:                Test-Simple
version:             0.60_02
abstract:            ~
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30
authored_by:         ~
distribution_type:   module
requires:     
    Test::Harness:                 2.03
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
