# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Simple
version:      0.53
version_from: lib/Test/Simple.pm
installdirs:  perl
requires:
    Test::Harness:                 2.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21_03
