--- #YAML:1.0
name:                Test-Simple
version:             0.64_01
abstract:            ~
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_03
author:              ~
distribution_type:   module
requires:     
    Test::Harness:                 2.03
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
