---
abstract: 'Basic utilities for writing tests.'
author:
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Simple
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: 1.13
  Test::Harness: 2.03
  perl: 5.006
resources:
  MailingList: http://lists.perl.org/list/perl-qa.html
  bugtracker: http://github.com/schwern/test-more/issues/
  homepage: http://github.com/schwern/test-more/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/schwern/test-more/
version: 1.001002
